// Utilities.
import { browserGlobals, modifiableArgs } from '#utilities/constants'

/** @type {import('eslint').Linter.RulesRecord} */
const rules = {
	'accessor-pairs': 'off',
	'array-callback-return': [ 'error', { allowImplicit: true } ],
	'arrow-body-style': [ 'error', 'as-needed', { requireReturnForObjectLiteral: false } ],
	'block-scoped-var': 'error',
	'callback-return': 'off',
	camelcase: [ 'error', { properties: 'never' } ],
	'capitalized-comments': 'off',
	'class-methods-use-this': [ 'error', { exceptMethods: [] } ],
	complexity: 'off',
	'consistent-return': 'error',
	'consistent-this': 'off',
	'constructor-super': 'error',
	curly: [ 'error', 'multi-line' ],
	'default-case': [ 'error', { commentPattern: '^no default$' } ],
	'default-case-last': 'error',
	'default-param-last': 'error',
	'dot-notation': [ 'error', { allowKeywords: true } ],
	eqeqeq: [ 'error', 'always', { null: 'ignore' } ],
	'for-direction': 'error',
	'func-call-spacing': [ 'error', 'never' ],
	'func-name-matching': 'off',
	'func-names': 'warn',
	'func-style': [ 'error', 'declaration', { allowArrowFunctions: true } ],
	'getter-return': [ 'error', { allowImplicit: true } ],
	'global-require': 'error',
	'grouped-accessor-pairs': 'error',
	'guard-for-in': 'error',
	'handle-callback-err': 'off',
	'id-denylist': 'off',
	'id-length': 'off',
	'id-match': 'off',
	'init-declarations': 'off',
	'lines-around-directive': [ 'error', { before: 'always', after: 'always' } ],
	'logical-assignment-operators': 'off',
	'max-classes-per-file': [ 'error', 1 ],
	'max-depth': 'off',
	'max-lines': 'off',
	'max-lines-per-function': 'off',
	'max-nested-callbacks': 'off',
	'max-params': 'off',
	'max-statements': [ 'error', 100, { ignoreTopLevelFunctions: true } ],

	'new-cap': [ 'error', {
		newIsCap: true,
		newIsCapExceptions: [],
		capIsNew: false,
		capIsNewExceptions: [ 'Immutable.Map', 'Immutable.Set', 'Immutable.List' ],
	} ],

	'newline-after-var': 'off',
	'newline-before-return': 'off',
	'no-alert': 'warn',
	'no-array-constructor': 'error',
	'no-async-promise-executor': 'error',
	'no-await-in-loop': 'error',
	'no-bitwise': 'error',
	'no-buffer-constructor': 'error',
	'no-caller': 'error',
	'no-case-declarations': 'error',
	'no-catch-shadow': 'off',
	'no-class-assign': 'error',
	'no-compare-neg-zero': 'error',
	'no-cond-assign': [ 'error', 'always' ],
	'no-console': 'warn',
	'no-const-assign': 'error',
	'no-constant-binary-expression': 'off',
	'no-constant-condition': 'warn',
	'no-constructor-return': 'error',
	'no-continue': 'off',
	'no-control-regex': 'error',
	'no-debugger': 'error',
	'no-delete-var': 'error',
	'no-div-regex': 'off',
	'no-dupe-args': 'error',
	'no-dupe-class-members': 'error',
	'no-dupe-else-if': 'error',
	'no-dupe-keys': 'error',
	'no-duplicate-case': 'error',
	'no-duplicate-imports': 'off',
	'no-else-return': [ 'error', { allowElseIf: false } ],
	'no-empty': 'error',
	'no-empty-character-class': 'error',
	'no-empty-function': [ 'error', { allow: [ 'arrowFunctions', 'functions', 'methods' ] } ],
	'no-empty-pattern': 'error',
	'no-empty-static-block': 'off',
	'no-eq-null': 'off',
	'no-eval': 'error',
	'no-ex-assign': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-extra-boolean-cast': 'error',
	'no-extra-label': 'error',
	'no-fallthrough': 'error',
	'no-func-assign': 'error',
	'no-global-assign': [ 'error', { exceptions: [] } ],
	'no-implicit-coercion': 'off',
	'no-implicit-globals': 'off',
	'no-implied-eval': 'error',
	'no-import-assign': 'error',
	'no-inline-comments': 'off',
	'no-inner-declarations': 'error',
	'no-invalid-regexp': 'error',
	'no-invalid-this': 'off',
	'no-irregular-whitespace': 'error',
	'no-iterator': 'error',
	'no-label-var': 'error',
	'no-labels': [ 'error', { allowLoop: false, allowSwitch: false } ],
	'no-lone-blocks': 'error',
	'no-lonely-if': 'error',
	'no-loop-func': 'error',
	'no-loss-of-precision': 'error',
	'no-magic-numbers': 'off',
	'no-misleading-character-class': 'error',
	'no-mixed-requires': 'off',
	'no-multi-assign': [ 'error' ],
	'no-multi-str': 'error',
	'no-native-reassign': 'off',
	'no-negated-condition': 'off',
	'no-negated-in-lhs': 'off',
	'no-nested-ternary': 'error',
	'no-new': 'error',
	'no-new-func': 'error',
	'no-new-native-nonconstructor': 'off',
	'no-new-object': 'error',
	'no-new-require': 'error',
	'no-new-symbol': 'error',
	'no-new-wrappers': 'error',
	'no-nonoctal-decimal-escape': 'error',
	'no-obj-calls': 'error',
	'no-object-constructor': 'off',
	'no-octal': 'error',
	'no-octal-escape': 'error',
	'no-param-reassign': [ 'error', { props: true, ignorePropertyModificationsFor: modifiableArgs } ],
	'no-path-concat': 'error',
	'no-plusplus': 'error',
	'no-process-env': 'off',
	'no-process-exit': 'off',
	'no-promise-executor-return': 'error',
	'no-proto': 'error',
	'no-prototype-builtins': 'error',
	'no-redeclare': 'error',
	'no-regex-spaces': 'error',
	'no-restricted-exports': [ 'error', { restrictedNamedExports: [ 'default', 'then' ] } ],

	'no-restricted-globals': [ 'error', {
		name: 'isFinite',
		message: "Use 'Number.isFinite' instead.",
	}, {
		name: 'isNaN',
		message: "Use 'Number.isNaN' instead.",
	} ].concat(browserGlobals.map(identifier => ({
		name: identifier,
		message: `Use 'window.${identifier}' instead.`,
	}))),

	'no-restricted-imports': 'off',
	'no-restricted-modules': 'off',

	'no-restricted-properties': [ 'error', ...[
		{ object: 'arguments', property: 'callee', message: 'arguments.callee is deprecated' },
		{ object: 'global', property: 'isFinite', message: 'Please use Number.isFinite instead' },
		{ object: 'self', property: 'isFinite', message: 'Please use Number.isFinite instead' },
		{ object: 'window', property: 'isFinite', message: 'Please use Number.isFinite instead' },
		{ object: 'global', property: 'isNaN', message: 'Please use Number.isNaN instead' },
		{ object: 'self', property: 'isNaN', message: 'Please use Number.isNaN instead' },
		{ object: 'window', property: 'isNaN', message: 'Please use Number.isNaN instead' },
		{ property: '__defineGetter__', message: 'Please use Object.defineProperty instead.' },
		{ property: '__defineSetter__', message: 'Please use Object.defineProperty instead.' },
		{ object: 'Math', property: 'pow', message: 'Use the exponentiation operator (**) instead.' },
		{ object: 'document', property: 'cookie', message: 'Do not use cookies.' },
		{ property: 'forEach', message: 'Please use for..of loops instead.' },
	] ],

	'no-restricted-syntax': [ 'error', {
		selector: 'ForInStatement',
		message: 'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
	}, {
		selector: 'LabeledStatement',
		message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
	}, {
		selector: 'WithStatement',
		message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
	}, {
		selector: 'CallExpression[name="execScript"]',
		message: 'Do not use the execScript functions.',
	} ],

	'no-return-assign': [ 'error', 'always' ],
	'no-return-await': 'error',
	'no-script-url': 'error',
	'no-self-assign': [ 'error', { props: false } ],
	'no-self-compare': 'error',
	'no-sequences': 'error',
	'no-setter-return': 'error',
	'no-shadow': 'error',
	'no-shadow-restricted-names': 'error',
	'no-spaced-func': 'off',
	'no-sparse-arrays': 'error',
	'no-sync': 'off',
	'no-template-curly-in-string': 'error',
	'no-ternary': 'off',
	'no-this-before-super': 'error',
	'no-throw-literal': 'error',
	'no-undef': 'error',
	'no-undef-init': 'error',
	'no-undefined': 'off',
	'no-underscore-dangle': [ 'error', { allow: [], allowAfterThis: false, allowAfterSuper: false, enforceInMethodNames: true } ],
	'no-unexpected-multiline': 'error',
	'no-unmodified-loop-condition': 'off',
	'no-unneeded-ternary': [ 'error', { defaultAssignment: false } ],
	'no-unreachable': 'error',
	'no-unreachable-loop': [ 'error', { ignore: [] } ],
	'no-unsafe-finally': 'error',
	'no-unsafe-negation': 'error',
	'no-unsafe-optional-chaining': [ 'error', { disallowArithmeticOperators: true } ],
	'no-unused-expressions': [ 'error', { allowShortCircuit: false, allowTernary: false, allowTaggedTemplates: false } ],
	'no-unused-labels': 'error',
	'no-unused-private-class-members': 'off',
	'no-unused-vars': [ 'error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true } ],
	'no-use-before-define': [ 'error', { functions: true, classes: true, variables: true } ],
	'no-useless-backreference': 'error',
	'no-useless-call': 'off',
	'no-useless-catch': 'error',
	'no-useless-computed-key': 'error',
	'no-useless-concat': 'error',
	'no-useless-constructor': 'error',
	'no-useless-escape': 'error',
	'no-useless-rename': [ 'error', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false } ],
	'no-useless-return': 'error',
	'no-var': 'error',
	'no-void': 'error',
	'no-warning-comments': [ 'warn', { location: 'anywhere', terms: [ 'BUG', 'HACK', 'FIXME', 'LATER', 'LATER2', 'TODO' ] } ],
	'no-with': 'error',
	'object-shorthand': [ 'error', 'always', { ignoreConstructors: false, avoidQuotes: true } ],
	'one-var': [ 'error', 'never' ],
	'operator-assignment': [ 'error', 'always' ],
	'prefer-arrow-callback': [ 'error', { allowNamedFunctions: false, allowUnboundThis: true } ],
	'prefer-const': [ 'error', { destructuring: 'any', ignoreReadBeforeAssign: true } ],

	'prefer-destructuring': [ 'error', {
		AssignmentExpression: { array: true, object: true },
		VariableDeclarator: { array: false, object: true },
	}, {
		enforceForRenamedProperties: false,
	} ],

	'prefer-exponentiation-operator': 'error',
	'prefer-named-capture-group': 'off',
	'prefer-numeric-literals': 'error',
	'prefer-object-has-own': 'off',
	'prefer-object-spread': 'error',
	'prefer-promise-reject-errors': [ 'error', { allowEmptyReject: true } ],
	'prefer-reflect': 'off',
	'prefer-regex-literals': [ 'error', { disallowRedundantWrapping: true } ],
	'prefer-rest-params': 'error',
	'prefer-spread': 'error',
	'prefer-template': 'error',
	radix: 'error',
	'require-atomic-updates': 'off',
	'require-await': 'off',
	'require-jsdoc': 'off',
	'require-unicode-regexp': 'off',
	'require-yield': 'error',
	'sort-imports': 'off',
	'sort-keys': 'off',
	'sort-vars': 'off',
	strict: [ 'error', 'never' ],
	'symbol-description': 'error',
	'unicode-bom': [ 'error', 'never' ],
	'use-isnan': 'error',
	'valid-jsdoc': 'off',
	'valid-typeof': [ 'error', { requireStringLiterals: true } ],
	'vars-on-top': 'error',
	yoda: 'error',
}

export default rules
