#!/usr/bin/env bash

source "$(git rev-parse --show-toplevel)/scripts/task-runner"

__task_default() {
    __describe "Install and activate Emsdk"

    if __exists emsdk; then
        return
    fi

    local EMSDK="./packages/shader-compressor/artifacts/emsdk/emsdk"

    "$EMSDK" install latest
    "$EMSDK" activate latest
}
