#!/usr/bin/env bash

function bootstrap() {
    unset -f bootstrap

    if test "$(command -v emsdk)"; then
        return
    fi

    cd packages/shader-compressor/artifacts/emsdk || exit 1

    if [ -v GITHUB_ACTIONS ]; then
        echo "::group::Install and activate Emsdk"
    fi

    EMSDK_KEEP_DOWNLOADS=1 \
    ./emsdk install latest
    ./emsdk activate latest

    if [ -v GITHUB_ACTIONS ]; then
        echo "::endgroup::"
    fi

    cd ../../../..
}

bootstrap "$@"
