#!/usr/bin/env bash

function bootstrap() {
    unset -f bootstrap
    set -euxo pipefail

    npm install --global npm || exit 1
    npm ci --ignore-scripts || exit 1
    npm ls --depth=0 || exit 1
    npm run build || exit 1
    npm test || exit 1
}

bootstrap "$@"
