#!/usr/bin/env bash

trap 'trap - EXIT && __startup' EXIT

__macos() {
    test "$(uname -s)" = "Darwin"
}

__linux() {
    test "$(uname -s)" = "Linux"
}

__exists() {
    test "$(command -v "$1")"
}

__invoke() {
	if __exists "$1"; then
		"$1"
	fi
}

__runall() {
    local TARGET

    for TARGET in "$@"; do
        __invoke "__task_$TARGET";
    done
}

__describe() {
    if [ "${GITHUB_ACTIONS:-}" == true ] && [ ! -z "$1" ]; then
        echo "::group::$1"
        trap 'trap "echo \"::endgroup::\" && trap - RETURN" RETURN' RETURN
    fi
}

__startup() {
    if __exists __task_default; then
        __runall default
    fi
}
