name: On release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release
    uses: ./.github/workflows/base.yml
    permissions:
      contents: read
      id-token: write
    with:
      release: true
    secrets: inherit
