name: On release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: recursive

    - name: Setup (CMake & Ninja)
      uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2

    - name: Setup (Ccache)
      run: |
        sudo rm -f /var/lib/man-db/auto-update && \
        sudo apt-get install -y ccache

    - name: Setup (Emscripten SDK)
      run: bash scripts/install-emsdk.sh

    - name: Setup (Node.js)
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24.x
        package-manager-cache: false

    - name: Setup (Yarn Berry)
      run: |
        npm install --global corepack && \
        corepack enable && \
        echo "Yarn v$(yarn --version)"

    - name: Setup (.NET)
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 #v6.0.0
      with:
        dotnet-version: 10.0.x
        dotnet-quality: 'ga'
        cache: true
        cache-dependency-path: packages/shader-compressor/packages.lock.json

    - name: Cache (dependencies · path resolution)
      id: yarn-cache
      run: echo "dir=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

    - name: Cache (dependencies)
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: yarn-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-${{ runner.arch }}-

    - name: Cache (build artifacts)
      id: cache-build-artifacts
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: .cache
        key: cache-build-artifacts-${{ github.head_ref || github.ref_name }}-${{ hashFiles('.git/modules/emsdk/HEAD', '.git/modules/glsl-optimizer/HEAD') }}
        restore-keys: |
          cache-build-artifacts-${{ github.head_ref || github.ref_name }}-

    - name: Cache (build artifacts · restoration)
      if: steps.cache-build-artifacts.outputs.cache-hit == 'true'
      run: bash scripts/cache-restore.sh

    - name: Install, Build and Test
      run: bash scripts/integration.sh

    - name: Collect code coverage
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        directory: coverage
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Cache (build artifacts · prepackage)
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: bash scripts/cache-prepack.sh

    - name: Publish
      run: yarn workspaces foreach -Av --no-private npm publish --provenance
