name: On release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'

    - name: Install, Build and Test
      run: bash scripts/integration
      env:
        CI: true

    - name: Upload collected code coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Publish the package
      run: npm publish --provenance --workspaces
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
